# Generated by Django 4.0.6 on 2022-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_edit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
