# Generated by Django 4.0.6 on 2022-07-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0003_team_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
