# Generated by Django 4.0.6 on 2022-07-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship', '0004_alter_profile_is_edit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
